PREFIX lexinfo: <https://lexinfo.net/ontology/3.0/lexinfo#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX tlkg: <https://w3id.org/thailex/ontology/>

SELECT ?sense ?sourceRecordId ?pos ?definition
WHERE {
  GRAPH <https://w3id.org/thailex/graph/lexitron> {
    ?entry a ontolex:LexicalEntry ;
           rdfs:label "ขัน"@th ;
           ontolex:sense ?sense .
    ?sense tlkg:hasDefinition ?definitionAssertion .
    ?definitionAssertion tlkg:definitionText ?definition ;
                         <http://www.w3.org/ns/prov#wasDerivedFrom> ?sourceRecord .
    ?sourceRecord tlkg:sourceRecordId ?sourceRecordId .
    OPTIONAL { ?sense lexinfo:partOfSpeech ?pos }
  }
}
ORDER BY ?sourceRecordId

